title:
  fr: M. Homme
  en: Mr. Guy

description:
  fr: La seule chose qui lui manque, c'est le pouvoir d'avoir un impact sur ce qu'il voit.
  en: The only thing he lacks is the power to have an impact on what he sees.
