title: WELTKERN

tabs:
  index:
    title: INDEX
    columns:
      - width: 1/2
        sections:
          __sectionProducts:
            type: fields
            fields:
              __titProducts:
                type: headline
                numbered: false
                label:
                  fr: "PRODUITS"
                  en: "PRODUCTS"
              pageProducts:
                type: pages
                required: true
                multiple: false
                translate: false
                layout: cardlets
                disabled: true
                label:
                  fr: "Liste des produits"
                  en: "Products list"
          __sectionFonts:
            type: fields
            fields:
              __titFonts:
                type: headline
                numbered: false
                label:
                  fr: "POLICES"
                  en: "FONTFACES"
              pageFonts:
                type: pages
                width: 1/2
                required: true
                multiple: false
                translate: false
                layout: cardlets
                disabled: true
                label:
                  fr: "Liste des polices"
                  en: "Fontfaces list"
              pageFontsSettings:
                type: pages
                width: 1/2
                required: true
                multiple: false
                translate: false
                layout: cardlets
                disabled: true
                label:
                  fr: "Paramètres des polices"
                  en: "Fontfaces settings"
          __sectionConfig:
            type: fields
            fields:
              __titConfig:
                type: headline
                numbered: false
                label:
                  fr: "CONFIGURATION"
                  en: "CONFIGURATION"
      - width: 1/2
        sections:
          __sectionPages:
            type: fields
            fields:
              __titPages:
                type: headline
                numbered: false
                label:
                  fr: "PAGES SPÉCIALES"
                  en: "SPECIAL PAGES"
              pageHome:
                type: pages
                required: true
                multiple: false
                translate: false
                layout: cardlets
                disabled: true
                label:
                  fr: "Page d'accueil"
                  en: "Home page"
                width: 1/2
              pageKerns:
                type: pages
                required: true
                multiple: false
                translate: false
                layout: cardlets
                disabled: true
                label:
                  fr: "Kerns"
                  en: "Kerns"
                width: 1/2
              pageAbout:
                type: pages
                required: true
                multiple: false
                translate: false
                layout: cardlets
                disabled: true
                label:
                  fr: "À propos"
                  en: "About"
                width: 1/2
              pageError:
                type: pages
                required: true
                multiple: false
                translate: false
                layout: cardlets
                disabled: true
                label:
                  fr: "Erreur"
                  en: "Error"
                width: 1/2
          __sectionBrands:
            type: fields
            fields:
              __titBrands:
                type: headline
                numbered: false
                label:
                  fr: "MARQUES"
                  en: "BRANDS"
          __sectionPeople:
            type: fields
            fields:
              __titPeople:
                type: headline
                numbered: false
                label:
                  fr: "PERSONNES"
                  en: "PEOPLE"
  settings:
    title:
      fr: "PARAMÈTRES"
      en: "SETTINGS"
    columns:
      - width: 1/2
        sections:
          __sectionTitles:
            type: fields
            fields:
              __titTitles:
                type: headline
                numbered: false
                label:
                  fr: "TITRES"
                  en: "TITLES"
                help:
                  fr: "Les variations de titres du site, selon l'emplacement et la langue.\nLe title principal est celui en haut du panel, et est éditable directement là."
                  en: "The site's title variations, according to the location and language.\nThe main title is the one at the top of the panel, and is editable directly there."
              titleShort:
                type: text
                width: 1/2
                label:
                  fr: "Titre court"
                  en: "Short title"
                help:
                  fr: "Utilisé notamment pour la version mobile du site, ou dans les endroits avec peu d'espace."
                  en: "Used especially for the mobile version of the site, or in places with little space."
              titleSimple:
                type: text
                width: 1/2
                label:
                  fr: "Titre simple"
                  en: "Simple title"
                help:
                  fr: "Utilisé dans les endroits où une forme plus simple est nécessaire."
                  en: "Used in places where a simpler form is needed."
              slogan:
                type: text
                label: "Slogan"
