title: Products

columns:
  left:
    width: 1/2
    sections:
      products:
        label:
          fr: Produits
          en: Products
        type: pages
        parent: site.find("products")
        templates:
          - product_book
          - product_tool
