title:
  fr: Livre
  en: Book

options:
  changeTitle: false
  changeTemplate:
    - product_book
    - product_tool

columns:
  - width: 2/3
    sections:
      infos:
        type: fields
        fields:
          multilineTitle:
            type: textarea
            label:
              fr: Titre
              en: Title
            size: tiny
            buttons: false
            width: 1/2
            help:
              fr: |
                Titre complet du livre, autorisant les retours à la ligne.
              en: |
                Full title of the book, allowing line breaks.
          multilineTitleSeparator:
            type: select
            label:
              fr: Séparateur
              en: Separator
            required: true
            default: dash
            width: 1/2
            options:
              space:
                fr: Espace
                en: Space
              dash:
                fr: Tiret
                en: Dash
              colon:
                fr: Deux points
                en: Colon
            help:
              fr: |
                Défini le séparateur entre les lignes du titre. Uniquement visible si le titre est multiligne, dans les endroits où une seule ligne est autorisée.
                Espace: <strong>{{ page.titleWithSeparator('space') }}</strong>
                Tiret: <strong>{{ page.titleWithSeparator('dash') }}</strong>
                Deux points: <strong>{{ page.titleWithSeparator('colon') }}</strong>
              en: |
                Defines the separator between the title lines. Only visible if the title is multiline, in places where only one line is allowed.
                Space: <strong>{{ page.titleWithSeparator('space') }}</strong>
                Dash: <strong>{{ page.titleWithSeparator('dash') }}</strong>
                Colon: <strong>{{ page.titleWithSeparator('colon') }}</strong>
          publisher:
            type: pages
            label:
              fr: Éditeur
              en: Publisher
            layout: cardlets
            multiple: false
            width: 1/2
            # query: site.find("publishers").children.filterBy("template", "publisher")
          price:
            translate: false
            label:
              fr: Prix
              en: Price
            type: number
            step: 0.05
            min: 0
            after:
              fr: CHF
              en: ""
            before:
              fr: ""
              en: "CHF"
            width: 1/2
          tags:
            tagset: test

          auto_kerns:
            translate: false
            label:
              fr: Kerns automatiques
              en: Auto kerns
            type: toggle
            default: true
            width: 1/2
            text:
              - fr: "Non"
                en: "No"
              - fr: "Oui"
                en: "Yes"
          kerns:
            translate: false
            label: Kerns
            type: number
            step: 1
            min: 0
            after: "K+"
            placeholder: "{{ page.kerns ?? 0}}"
            when:
              auto_kerns: false
            width: 1/2
          __spacer:
            type: gap
            width: 1/2
            when:
              auto_kerns: true
          image:
            translate: false
            type: url
            label:
              fr: Image
              en: Image
            width: 1/2
          cover:
            translate: false
            type: files
            label:
              fr: Couverture
              en: Cover
            multiple: false
          stock:
            translate: false
            label:
              fr: Stock
              en: Stock
            type: number
            step: 1
            min: 0
            width: 1/2

  - width: 1/3
    sections:
      meta:
        type: fields
        fields:
          __titMeta:
            type: headline
            numbered: false
            label:
              fr: MÉTADONNÉES
              en: METADATA
          supplier:
            type: pages
            width: 1/2
            label:
              fr: Fournisseur
              en: Supplier
            query: site.find("suppliers").children.filterBy("template", "supplier")
            search: true
            layout: cardlets
            multiple: false
          # Start Old Weltkern -------------------------------------
          oldWeltkern:
            type: object
            label:
              fr: Ancien Weltkern
              en: Old Weltkern
            help:
              fr: Contient les informations de l'ancien Weltkern, pour la migration mais aussi pour rendre le nouveau site rétrocompatible.
              en: Contains the old Weltkern informations, for the migration but also to make the new site retrocompatible.
            fields:
              title:
                type: text
                disabled: true
                label:
                  fr: Titre
                  en: Title
              slug:
                type: text
                disabled: true
                width: 2/3
                label:
                  fr: Slug Wordpress
                  en: Wordpress slug
              id:
                type: number
                disabled: true
                width: 1/3
                label:
                  fr: ID Wordpress
                  en: Wordpress ID
                step: 1
              isbn:
                type: text
                disabled: true
                width: 1/2
                label: ISBN
              price:
                type: number
                disabled: true
                width: 1/4
                label:
                  fr: Prix
                  en: Price
                after: CHF
              weight:
                type: number
                disabled: true
                width: 1/4
                label:
                  fr: Poids
                  en: Weight
                after: kg
              author:
                type: object
                fields:
                  name:
                    type: text
                    disabled: true
                    label:
                      fr: Nom
                      en: Name
                    width: 3/4
                  id:
                    type: number
                    disabled: true
                    label: ID
                    width: 1/4
              description:
                type: textarea
                disabled: true
                buttons: false
                width: 2/3
                size: medium
              details:
                type: textarea
                disabled: true
                buttons: false
                width: 1/3
                size: medium
              gallery:
                type: structure
                width: 1/2
                disabled: true
                label:
                  fr: Galerie d'images
                  en: Images gallery
                help:
                  fr: Liens vers la galerie d'images, sur le site Wordpress.
                  en: Links to the images gallery, on the Wordpress site.
                fields:
                  url:
                    type: url
                    width: 2/3
                    label:
                      fr: URL de la galerie
                      en: Gallery URL
                  id:
                    type: number
                    width: 1/3
                    label:
                      fr: ID du média Wordpress
                      en: Wordpress media ID
                    step: 1
              tags:
                type: structure
                width: 1/2
                disabled: true
                label:
                  fr: Tags
                  en: Tags
                help:
                  fr: Tags Wordpress
                  en: Wordpress tags
                fields:
                  name:
                    type: text
                    width: 2/3
                    label:
                      fr: Nom
                      en: Name
                  id:
                    type: number
                    width: 1/3
                    label:
                      fr: ID Wordpress
                      en: Wordpress ID
                    step: 1
          # End Old Weltkern ---------------------------------------
      files:
        type: files
        label:
          fr: Gestionnaire de fichiers
          en: Files handler
        help:
          fr: |
            Permet de télécharger des fichiers, d'en supprimer ou d'en ajouter, mais ne les rend pas automatiquement visibles.
