title: Products

columns:
  - sections:
      products:
        type: pages
        label:
          fr: Produits
          en: Products

        templates:
          - product_book
          - product_tool
        parent: site.find("products")

        limit: 30
        search: true

        layout: table
        columns:
          author:
            width: 2/11
          publisher:
            width: 2/11
          price:
            width: 1/11
            align: center
            after: "CHF"
            value: "{{ page.price }}"
