title:
  fr: Livre
  en: Book

options:
  changeTemplate:
    - product_book
    - product_tool

sections:
  infos:
    type: fields
    extends: fields/product
    fields:
      brand:
        label:
          fr: Éditeur
          en: Publisher
