title: Products

columns:
  left:
    width: 1/2
    sections:
      books:
        label:
          fr: Livres
          en: Books
        type: pages
        templates:
          - product_book
          - product_tool
