title: Products

columns:
  left:
    width: 1/2
    sections:
      books:
        label:
          fr: Livres
          en: Books
        type: pages
        template: product_book
  right:
    width: 1/2
    sections:
      tools:
        label:
          fr: Outils
          en: Tools
        type: pages
        template: product_tool
