title:
  fr: Outil
  en: Tool

options:
  changeTemplate:
    - product_book
    - product_tool

sections:
  infos:
    type: fields
    extends: fields/product
    fields:
      brand:
        label:
          fr: Marque
          en: Brand
