title:
  fr: Réglages généraux des polices
  en: General fonts settings

icon: settings

options:
  changeSlug: false
  changeStatus: false
  changeTemplate: false
  changeTitle: false
  create: false
  delete: false
  duplicate: false

tabs:
  texts:
    label:
      fr: Textes
      en: Texts
    fields:
      texts:
        type: structure
        label:
          fr: Lignes de texte
          en: Texts lines
        help:
          fr: |
            Lignes de texte à afficher aléatoirement dans les pages de polices.
        fields:
          text:
            type: textarea
            label:
              fr: Texte
              en: Text
            buttons: false
